name: Deploy demo web site
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build front
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm install
      - run: cd test
      - run: npm install
      - run: npm run build

      - name: Send files to server
        uses: Creepios/sftp-action@v1.0.5
        with:
          host: 151.80.58.137
          port: 10
          username: 'macaron'
          password: 'password'
          localPath: './dist/'
          remotePath: '/var/www/web-basic/'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
